<?php

namespace PonderSource\Peppol\Constants;
class eas
{

    
    const SYSTEM_INFORMATION_ET_REPERTOIRE_DES_ENTREPRISE_ET_DES_ETABLISSEMENTS_SIRENE = "0002";

    
    const ORGANISATIONSNUMMER_SWEDISH_LEGAL_ENTITIES = "0007";

    
    const SIRETCODE = "0009";

    
    const LYTUNNUS = "0037";

    
    const DATA_UNIVERSAL_NUMBERING_SYSTEM_DUNS_NUMBER = "0060";

    
    const EAN_LOCATION_CODE = "0088";

    
    const DANISH_CHAMBER_OF_COMMERCE_SCHEME_EDIRA_COMPLIANT = "0096";

    
    const FTI__EDIFORUM_ITALIA_EDIRA_COMPLIANT = "0097";

    
    const VERENIGING_VAN_KAMERS_VAN_KOOPHANDEL_EN_FABRIEKEN_IN_NEDERLAND_ASSOCIATION_OF_CHAMBERS_OF_COMMERCE_AND_INDUSTRY_IN_THE_NETHERLANDS_SCHEME_EDIRA_COMPLIANT = "0106";

    
    const DIRECTORATES_OF_THE_EUROPEAN_COMMISSION = "0130";

    
    const SIA_OBJECT_IDENTIFIERS = "0135";

    
    const SECETI_OBJECT_IDENTIFIERS = "0142";

    
    const AUSTRALIAN_BUSINESS_NUMBER_ABN_SCHEME = "0151";

    
    const NUMRO_DIDENTIFICATION_SUISSE_DES_ENTERPRISES_IDE_SWISS_UNIQUE_BUSINESS_IDENTIFICATION_NUMBER_UIDB = "0183";

    
    const DIGSTORG = "0184";

    
    const DUTCH_ORIGINATORS_IDENTIFICATION_NUMBER = "0190";

    
    const CENTRE_OF_REGISTERS_AND_INFORMATION_SYSTEMS_OF_THE_MINISTRY_OF_JUSTICE = "0191";

    
    const ENHETSREGISTERET_VED_BRONNOYSUNDREGISTERNE = "0192";

    
    const UBLBE_PARTY_IDENTIFIER = "0193";

    
    const SINGAPORE_UEN_IDENTIFIER = "0195";

    
    const KENNITALA__ICELAND_LEGAL_ID_FOR_INDIVIDUALS_AND_LEGAL_ENTITIES = "0196";

    
    const ERSTORG = "0198";

    
    const LEGAL_ENTITY_IDENTIFIER_LEI = "0199";

    
    const LEGAL_ENTITY_CODE_LITHUANIA = "0200";

    
    const CODICE_UNIVOCO_UNIT_ORGANIZZATIVA_IPA = "0201";

    
    const INDIRIZZO_DI_POSTA_ELETTRONICA_CERTIFICATA = "0202";

    
    const LEITWEGID = "0204";

    
    const NUMERO_DENTREPRISE__ONDERNEMINGSNUMMER__UNTERNEHMENSNUMMER = "0208";

    
    const GS_IDENTIFICATION_KEYS = "0209";

    
    const CODICE_FISCALE = "0210";

    
    const PARTITA_IVA = "0211";

    
    const FINNISH_ORGANIZATION_IDENTIFIER = "0212";

    
    const FINNISH_ORGANIZATION_VALUE_ADD_TAX_IDENTIFIER = "0213";

    
    const DANISH_MINISTRY_OF_THE_INTERIOR_AND_HEALTH = "9901";

    
    const UFFICIO_RESPONSABILE_GESTIONE_PARTITE_IVA = "9906";

    
    const TAX_AUTHORITY = "9907";

    
    const HUNGARY_VAT_NUMBER = "9910";

    
    const BUSINESS_REGISTERS_NETWORK = "9913";

    
    const STERREICHISCHE_UMSATZSTEUERIDENTIFIKATIONSNUMMER = "9914";

    
    const STERREICHISCHES_VERWALTUNGS_BZW_ORGANISATIONSKENNZEICHEN = "9915";

    
    const SOCIETY_FOR_WORLDWIDE_INTERBANK_FINANCIAL_TELECOMMUNICATION_SWIFT = "9918";

    
    const KENNZIFFER_DES_UNTERNEHMENSREGISTERS = "9919";

    
    const AGENCIA_ESPAOLA_DE_ADMINISTRACIN_TRIBUTARIA = "9920";

    
    const ANDORRA_VAT_NUMBER = "9922";

    
    const ALBANIA_VAT_NUMBER = "9923";

    
    const BOSNIA_AND_HERZEGOVINA_VAT_NUMBER = "9924";

    
    const BELGIUM_VAT_NUMBER = "9925";

    
    const BULGARIA_VAT_NUMBER = "9926";

    
    const SWITZERLAND_VAT_NUMBER = "9927";

    
    const CYPRUS_VAT_NUMBER = "9928";

    
    const CZECH_REPUBLIC_VAT_NUMBER = "9929";

    
    const GERMANY_VAT_NUMBER = "9930";

    
    const ESTONIA_VAT_NUMBER = "9931";

    
    const UNITED_KINGDOM_VAT_NUMBER = "9932";

    
    const GREECE_VAT_NUMBER = "9933";

    
    const CROATIA_VAT_NUMBER = "9934";

    
    const IRELAND_VAT_NUMBER = "9935";

    
    const LIECHTENSTEIN_VAT_NUMBER = "9936";

    
    const LITHUANIA_VAT_NUMBER = "9937";

    
    const LUXEMBURG_VAT_NUMBER = "9938";

    
    const LATVIA_VAT_NUMBER = "9939";

    
    const MONACO_VAT_NUMBER = "9940";

    
    const MONTENEGRO_VAT_NUMBER = "9941";

    
    const MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF_VAT_NUMBER = "9942";

    
    const MALTA_VAT_NUMBER = "9943";

    
    const NETHERLANDS_VAT_NUMBER = "9944";

    
    const POLAND_VAT_NUMBER = "9945";

    
    const PORTUGAL_VAT_NUMBER = "9946";

    
    const ROMANIA_VAT_NUMBER = "9947";

    
    const SERBIA_VAT_NUMBER = "9948";

    
    const SLOVENIA_VAT_NUMBER = "9949";

    
    const SLOVAKIA_VAT_NUMBER = "9950";

    
    const SAN_MARINO_VAT_NUMBER = "9951";

    
    const TURKEY_VAT_NUMBER = "9952";

    
    const HOLY_SEE_VATICAN_CITY_STATE_VAT_NUMBER = "9953";

    
    const SWEDISH_VAT_NUMBER = "9955";

    
    const FRENCH_VAT_NUMBER = "9957";
}